name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use GH_TOKEN
      run: |
        echo "Using GH_TOKEN in workflow"
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/user