name: Update README with Repo Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Calculate Total Repo Size and Stats
        id: repo_stats
        run: |
          total_size=0
          stars=0
          forks=0

          # Fetch all repositories
          repos=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/users/DipyomoyBarua/repos?per_page=100" | jq -r '.[] | .full_name')

          # Check if repos is empty
          if [ -z "$repos" ]; then
            echo "No repositories found or error fetching repositories."
            exit 1
          fi

          # Iterate through each repository
          for repo in $repos; do
            repo_size=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$repo" | jq -r '.size')
            repo_stars=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$repo" | jq -r '.stargazers_count')
            repo_forks=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$repo" | jq -r '.forks_count')

            # Check if any values are null or empty
            if [ -z "$repo_size" ]; then repo_size=0; fi
            if [ -z "$repo_stars" ]; then repo_stars=0; fi
            if [ -z "$repo_forks" ]; then repo_forks=0; fi

            total_size=$((total_size + repo_size))
            stars=$((stars + repo_stars))
            forks=$((forks + repo_forks))
          done

          last_commit=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Set the output variables
          echo "::set-output name=total_size::$((total_size / 1024))" # Convert to MB
          echo "::set-output name=stars::$stars"
          echo "::set-output name=forks::$forks"
          echo "::set-output name=last_commit::$last_commit"

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update README
        run: |
          sed -i "s/Total Repo Size:.*/Total Repo Size: ${{ steps.repo_stats.outputs.total_size }} MB/" README.md
          sed -i "s/Last Commit:.*/Last Commit: ${{ steps.repo_stats.outputs.last_commit }}/" README.md
          sed -i "s/Stars:.*/Stars: ${{ steps.repo_stats.outputs.stars }}/" README.md
          sed -i "s/Forks:.*/Forks: ${{ steps.repo_stats.outputs.forks }}/" README.md

      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update README with latest repo stats"
          git push
