name: Update README with Repo Stats

# Triggers the workflow on push to the main branch and on a scheduled basis (every hour)
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Calculate the total size of all repositories and gather other statistics
      - name: Calculate Total Repo Size and Stats
        id: repo_stats
        run: |
          total_size=0
          stars=0
          forks=0
          repos=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/users/DipyomoyBarua/repos?per_page=100" | jq -r '.[].full_name')

          for repo in $repos; do
            repo_size=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$repo" | jq -r '.size')
            repo_stars=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$repo" | jq -r '.stargazers_count')
            repo_forks=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$repo" | jq -r '.forks_count')

            total_size=$((total_size + repo_size))
            stars=$((stars + repo_stars))
            forks=$((forks + repo_forks))
          done

          last_commit=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Set the output variables
          echo "::set-output name=total_size::$((total_size / 1024))" # Convert to MB
          echo "::set-output name=stars::$stars"
          echo "::set-output name=forks::$forks"
          echo "::set-output name=last_commit::$last_commit"

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Update the README.md file with the latest statistics
      - name: Update README
        run: |
          sed -i "s/Total Repo Size:.*/Total Repo Size: ${{ steps.repo_stats.outputs.total_size }} MB/" README.md
          sed -i "s/Last Commit:.*/Last Commit: ${{ steps.repo_stats.outputs.last_commit }}/" README.md
          sed -i "s/Stars:.*/Stars: ${{ steps.repo_stats.outputs.stars }}/" README.md
          sed -i "s/Forks:.*/Forks: ${{ steps.repo_stats.outputs.forks }}/" README.md

      # Commit the changes to the README file
      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update README with latest repo stats"
          git push
