name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Calculate Repository Stats
        id: calc_stats
        run: |
          # Fetch and calculate the required stats
          TOTAL_SIZE=$(du -sh . | cut -f1 | sed 's/M/ MB/')
          LAST_COMMIT=$(git log -1 --format=%cd)
          
          # Fetch data from GitHub API with PAT
          repos_response=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" "https://api.github.com/users/DipyomoyBarua/repos?per_page=100")
          repos=$(echo "$repos_response" | jq -r '.[] | select(.fork==false) | .full_name')

          # Initialize the counters
          total_stars=0
          total_forks=0

          for repo in $repos; do
            repo_response=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" "https://api.github.com/repos/$repo")
            stars=$(echo "$repo_response" | jq -r '.stargazers_count')
            forks=$(echo "$repo_response" | jq -r '.forks_count')
            total_stars=$((total_stars + stars))
            total_forks=$((total_forks + forks))
          done

          # Export the totals to environment variables
          echo "STARS=${total_stars}" >> $GITHUB_ENV
          echo "FORKS=${total_forks}" >> $GITHUB_ENV

          echo "TOTAL_SIZE=${TOTAL_SIZE}" >> $GITHUB_ENV
          echo "LAST_COMMIT=${LAST_COMMIT}" >> $GITHUB_ENV
          
      - name: Debug Environment Variables
        run: |
          echo "TOTAL_SIZE=${{ env.TOTAL_SIZE }}"
          echo "LAST_COMMIT=${{ env.LAST_COMMIT }}"
          echo "STARS=${{ env.STARS }}"
          echo "FORKS=${{ env.FORKS }}"
        
      - name: Commit and Push Changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Update README with latest stats"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
