name: Update README with Repo Stats

# Triggers the workflow on push to the main branch and on a scheduled basis (every hour)
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Calculate the total size of all repositories and gather other statistics
      - name: Calculate Total Repo Size and Stats
        id: repo_stats
        run: |
          total_size=0
          stars=0
          forks=0

          # Fetch all repository data
          repos=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/users/DipyomoyBarua/repos?per_page=100" | jq -r '.[].full_name')

          # Loop through each repository to get its size, stars, and forks
          for repo in $repos; do
            repo_data=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$repo")
            repo_size=$(echo "$repo_data" | jq -r '.size')
            repo_stars=$(echo "$repo_data" | jq -r '.stargazers_count')
            repo_forks=$(echo "$repo_data" | jq -r '.forks_count')

            total_size=$((total_size + repo_size))
            stars=$((stars + repo_stars))
            forks=$((forks + repo_forks))
          done

          # Get the last commit date from the first repository (for simplicity)
          last_commit=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/$(echo $repos | head -n 1)" | jq -r '.pushed_at')

          # Set the output variables
          echo "total_size=$((total_size / 1024))" >> $GITHUB_ENV # Convert to MB
          echo "stars=$stars" >> $GITHUB_ENV
          echo "forks=$forks" >> $GITHUB_ENV
          echo "last_commit=$last_commit" >> $GITHUB_ENV

      # Update the README.md file with the latest statistics
      - name: Update README
        run: |
          sed -i "s/Total Repo Size:.*/Total Repo Size: ${{ env.total_size }} MB/" README.md
          sed -i "s/Last Commit:.*/Last Commit: ${{ env.last_commit }}/" README.md
          sed -i "s/Stars:.*/Stars: ${{ env.stars }}/" README.md
          sed -i "s/Forks:.*/Forks: ${{ env.forks }}/" README.md

      # Commit the changes to the README file
      - name: Commit Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update README with latest repo stats"
          git push
