name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug GH_TOKEN
      run: |
        echo "GH_TOKEN is present, but not displayed for security reasons."
        echo "Testing GH_TOKEN access..."
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/user
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
