name: Token Debugging

on: [push]

jobs:
  check-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check GH_TOKEN
      run: |
        echo "Testing GH_TOKEN access..."
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/user
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
